version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY='1z5y(xt8eq@#xt4j#@x)jr!a4tm=ue2#3at(@vh8+8zb0r)zes'
      - DEBUG=1
    # command: gunicorn main.wsgi:application --bind 0.0.0.0:8000 #python3 manage.py runserver 0.0.0.0:8000 #gunicorn main.wsgi:application --bind 0.0.0.0:8000

  # nginx:
  #   build: ./nginx
  #   ports:
  #     - 8001:80
  #   volumes:
  #     - ./nginx/conf:/etc/nginx/conf.d # - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
  #   depends_on:
  #     - web
